export const reportsData = [
  { id: 1, name: "Q4 Sales Analysis", pharmacy: "MediCare Pharmacy", date: "March 15th, 2024", status: "Failed", generatedBy: "Super Admin", type: "Sales" },
  { id: 2, name: "Monthly Compliance Check", pharmacy: "HealthHub Pharmacy", date: "March 10th, 2024", status: "Review", generatedBy: "Admin B", type: "Compliance" },
  { id: 3, name: "User Growth Q1", pharmacy: "MediConnect Platform", date: "March 5th, 2024", status: "Completed", generatedBy: "Super Admin", type: "Sales" },
  { id: 4, name: "Inventory Turnover", pharmacy: "City Drugs", date: "February 28th, 2024", status: "Review", generatedBy: "Admin C", type: "Pharmacy Performance" },
  { id: 5, name: "Pharmacy Audit Report", pharmacy: "MediCare Pharmacy", date: "February 20th, 2024", status: "Pending", generatedBy: "Super Admin", type: "Compliance" },
  { id: 6, name: "Sales by Region", pharmacy: "MediConnect Platform", date: "February 18th, 2024", status: "Failed", generatedBy: "Admin A", type: "Sales" },
  { id: 7, name: "Prescription Trends", pharmacy: "HealthHub Pharmacy", date: "February 12th, 2024", status: "Completed", generatedBy: "Admin B", type: "Pharmacy Performance" },
  { id: 8, name: "Customer Feedback Summary", pharmacy: "City Drugs", date: "February 5th, 2024", status: "Review", generatedBy: "Super Admin", type: "Compliance" },
  { id: 1, name: "Q4 Sales Analysis", pharmacy: "MediCare Pharmacy", date: "March 15th, 2024", status: "Failed", generatedBy: "Super Admin", type: "Sales" },
  { id: 2, name: "Monthly Compliance Check", pharmacy: "HealthHub Pharmacy", date: "March 10th, 2024", status: "Review", generatedBy: "Admin B", type: "Compliance" },
  { id: 3, name: "User Growth Q1", pharmacy: "MediConnect Platform", date: "March 5th, 2024", status: "Completed", generatedBy: "Super Admin", type: "Sales" },
  { id: 4, name: "Inventory Turnover", pharmacy: "City Drugs", date: "February 28th, 2024", status: "Review", generatedBy: "Admin C", type: "Pharmacy Performance" },
  { id: 5, name: "Pharmacy Audit Report", pharmacy: "MediCare Pharmacy", date: "February 20th, 2024", status: "Pending", generatedBy: "Super Admin", type: "Compliance" },
  { id: 6, name: "Sales by Region", pharmacy: "MediConnect Platform", date: "February 18th, 2024", status: "Failed", generatedBy: "Admin A", type: "Sales" },
  { id: 7, name: "Prescription Trends", pharmacy: "HealthHub Pharmacy", date: "February 12th, 2024", status: "Completed", generatedBy: "Admin B", type: "Pharmacy Performance" },
  { id: 8, name: "Customer Feedback Summary", pharmacy: "City Drugs", date: "February 5th, 2024", status: "Review", generatedBy: "Super Admin", type: "Compliance" },
];
