// Mock backend data for Profile pages
// Designed similarly to `src/shared/data.js` so components can import realistic sample data.
export const currentUser = {
  id: 9001,
  firstName: "Mazen",
  lastName: "Ahmed",
  fullName: "Mazen Ahmed",
  email: "mazen.ahmed@example.com",
  avatar: "/avatars/user-9001.jpg",
  phone: "+20 100 000 0000",
  dob: "1990-05-12",
  joined: "2023-03-18",
  role: "customer",
  conversations : [
    {
      id: 'alice',
      name: 'Alice Johnson',
      avatar: 'https://i.pravatar.cc/150?img=1',
      lastMessage: 'Thank you for the update!',
      time: '10:30 AM',
    },
    {
      id: 'bob',
      name: 'Bob Smith',
      avatar: 'https://i.pravatar.cc/150?img=12',
      lastMessage: 'Sure, I\'ll send it over.',
      time: 'Yesterday',
    },
    {
      id: 'charlie',
      name: 'Charlie Brown',
      avatar: 'https://i.pravatar.cc/150?img=13',
      lastMessage: 'Okay, I understand.',
      time: 'Mon',
    },
    {
      id: 'diana',
      name: 'Diana Prince',
      avatar: 'https://i.pravatar.cc/150?img=5',
      lastMessage: 'Thanks for the quick response!',
      time: 'Last Week',
    },
    {
      id: 'eve',
      name: 'Eve Adams',
      avatar: 'https://i.pravatar.cc/150?img=9',
      lastMessage: 'Yes, that works for me.',
      time: 'Last Month',
    },
  ],
  preferences: {
    newsletter: true,
    smsAlerts: false,
  },
  orders: [
    {
      id: "ORD-001",
      name: "Aisha Sharma",
      date: "2024-07-28",
      status: "Delivered",
      total: "₹1,250.00",
      paymentMethod: "Card",
        addresses: 
    {
      street: "12 Nile St",
      city: "Cairo",
      additionalDirections: "Near the central park",
      postalCode: "11511",
      phone: "+20 100 000 0000",
    },
      items: [
        {
          id: 1,
          name: "Aspirin",
          medicineImage: "/aspirin.jpg",
          price: 100,
          status: "Available",
          distance: "2.5km",
          category: "teblets",
          pharmacy: "Pharmacy A",
          description: "this is aspirin",
          quantity: 2,
        },
      ],
    },
    {
      id: "ORD-002",
      name: "Rajesh Kumar",
      date: "2024-07-27",
      status: "Shipped",
      total: "₹899.50",
      paymentMethod: "cash",
        addresses: 
    {
      street: "12 Nile St",
      city: "Cairo",
      additionalDirections: "Near the central park",
      postalCode: "11511",
      phone: "+20 100 000 0000",
    },
      items: [
        {
          id: 1,
          name: "Aspirin",
          medicineImage: "/aspirin.jpg",
          price: 100,
          status: "Available",
          distance: "2.5km",
          category: "teblets",
          pharmacy: "Pharmacy A",
          description: "this is aspirin",
          quantity: 2,
        },
      ],
    },
    {
      id: "ORD-003",
      name: "Mazen Ahmed",
      date: "2024-07-26",
      status: "Pending",
      total: "₹2,100.00",
      paymentMethod: "cash",
        addresses: 
    {
      street: "12 Nile St",
      city: "Cairo",
      additionalDirections: "Near the central park",
      postalCode: "11511",
      phone: "+20 100 000 0000",
    },
      items: [
        {
          id: 1,
          name: "Aspirin",
          medicineImage: "/aspirin.jpg",
          price: 100,
          status: "Available",
          distance: "2.5km",
          category: "teblets",
          pharmacy: "Pharmacy A",
          description: "this is aspirin",
          quantity: 2,
        },
      ],
    },
    {
      id: "ORD-004",
      name: "Lina Ali",
      email: "lina@example.com",
      date: "2024-07-25",
      status: "Processing",
      total: "₹700.00",
      paymentMethod: "cash",
        addresses: 
    {
      street: "12 Nile St",
      city: "Cairo",
      additionalDirections: "Near the central park",
      postalCode: "11511",
      phone: "+20 100 000 0000",
    },
      items: [
        {
          id: 1,
          name: "Aspirin",
          medicineImage: "/aspirin.jpg",
          price: 100,
          status: "Available",
          distance: "2.5km",
          category: "teblets",
          pharmacy: "Pharmacy A",
          description: "this is aspirin",
          quantity: 2,
        },
      ],
    },
    {
      id: "ORD-005",
      name: "Omar Khaled",
      date: "2024-07-24",
      status: "Delivered",
      total: "₹1,050.00",
      paymentMethod: "cash",
        addresses: 
    {
      street: "12 Nile St",
      city: "Cairo",
      additionalDirections: "Near the central park",
      postalCode: "11511",
      phone: "+20 100 000 0000",
    },
      items: [
        {
          id: 1,
          name: "Aspirin",
          medicineImage: "/aspirin.jpg",
          price: 100,
          status: "Available",
          distance: "2.5km",
          category: "teblets",
          pharmacy: "Pharmacy A",
          description: "this is aspirin",
          quantity: 2,
        },
      ],
    },
    {
      id: "ORD-006",
      name: "Sarah Mohamed",
      date: "2024-07-23",
      status: "Cancelled",
      total: "₹1,200.00",
      paymentMethod: "cash",
        addresses: 
    {
      street: "12 Nile St",
      city: "Cairo",
      additionalDirections: "Near the central park",
      postalCode: "11511",
      phone: "+20 100 000 0000",
    },
      items: [
        {
          id: 1,
          name: "Aspirin",
          medicineImage: "/aspirin.jpg",
          price: 100,
          status: "Available",
          distance: "2.5km",
          category: "teblets",
          pharmacy: "Pharmacy A",
          description: "this is aspirin",
          quantity: 2,
        },
      ],
    },
    {
      id: "ORD-007",
      name: "Kareem Nabil",
      date: "2024-07-22",
      status: "Processing",
      total: "₹880.00",
      paymentMethod: "cash",
        addresses: 
    {
      street: "12 Nile St",
      city: "Cairo",
      additionalDirections: "Near the central park",
      postalCode: "11511",
      phone: "+20 100 000 0000",
    },
      items: [
        {
          id: 1,
          name: "Aspirin",
          medicineImage: "/aspirin.jpg",
          price: 100,
          status: "Available",
          distance: "2.5km",
          category: "teblets",
          pharmacy: "Pharmacy A",
          description: "this is aspirin",
          quantity: 2,
        },
      ],
    },
    {
      id: "ORD-008",
      name: "Hana Youssef",
      date: "2024-07-21",
      status: "Pending",
      total: "₹960.00",
      paymentMethod: "cash",
      addresses: 
    {
      street: "12 Nile St",
      city: "Cairo",
      additionalDirections: "Near the central park",
      postalCode: "11511",
      phone: "+20 100 000 0000",
    },
      items: [
        {
          id: 1,
          name: "Aspirin",
          medicineImage: "/aspirin.jpg",
          price: 100,
          status: "Available",
          distance: "2.5km",
          category: "teblets",
          pharmacy: "Pharmacy A",
          description: "this is aspirin",
          quantity: 2,
        },
      ],
    },
  ],

};
