import React from "react";
import styles from "./ReportsTable.module.css";
import { Trash2, Eye } from "lucide-react";

export default function ReportsTable({ reports, onDelete }) {
  return (
    <div className={styles.tableContainer}>
      <h2 className={styles.tableTitle}>Generated Reports</h2>
      <table className={styles.table}>
        <thead>
          <tr>
            <th>#</th>
            <th>Report Name</th>
            <th>Pharmacy</th>
            <th>Date Generated</th>
            <th>Status</th>
            <th>Generated By</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {reports.map((r, index) => (
            <tr key={r.id}>
              <td>{index + 1}</td>
              <td>{r.name}</td>
              <td>{r.pharmacy}</td>
              <td>{r.date}</td>
              <td>
                <span className={`${styles.status} ${styles[r.status.toLowerCase()]}`}>
                  {r.status}
                </span>
              </td>
              <td>{r.generatedBy}</td>
              <td>
                <button className={styles.iconBtn}><Eye size={18} /></button>
                <button className={styles.iconBtn} onClick={() => onDelete(r.id)}>
                  <Trash2 size={18} />
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
